name: VillagerTalk
main: com.erigitic.main.VillagerTalk
version: 1.0.0

commands:
    create:
        description: Create MobTalk mob
        usage: /create <name>
    message:
        description: Set mob message
        usage: /message <message>
    item:
        description: Set mob item
        usage: /item <itemid>
    remove:
        description: Remove mob
        usage: /remove <mobName>